<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"电表管理",
                        "menuJump":"列表",
                        "tableName":"dianbiao"
                    }
                    ,
                    {
                        "buttons":[                            
							"删除"
                        ],
                        "menu":"电表缴费管理",
                        "menuJump":"列表",
                        "tableName":"dianbiaoList"
                    }
                ],
                "menu":"电表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"ETC管理",
                        "menuJump":"列表",
                        "tableName":"etc"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"						
                        ],
                        "menu":"ETC缴费管理",
                        "menuJump":"列表",
                        "tableName":"etcList"
                    }
                ],
                "menu":"ETC管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"供暖管理",
                        "menuJump":"列表",
                        "tableName":"gongnuan"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"
                        ],
                        "menu":"供暖缴费管理",
                        "menuJump":"列表",
                        "tableName":"gongnuanList"
                    }
                ],
                "menu":"供暖管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"固话管理",
                        "menuJump":"列表",
                        "tableName":"guhua"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"
                        ],
                        "menu":"固话缴费管理",
                        "menuJump":"列表",
                        "tableName":"guhuaList"
                    }
                ],
                "menu":"固话管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宽带管理",
                        "menuJump":"列表",
                        "tableName":"kuandai"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"
                        ],
                        "menu":"宽带缴费管理",
                        "menuJump":"列表",
                        "tableName":"kuandaiList"
                    }
                ],
                "menu":"宽带管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"燃气表管理",
                        "menuJump":"列表",
                        "tableName":"ranqibiao"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"
                        ],
                        "menu":"燃气表缴费管理",
                        "menuJump":"列表",
                        "tableName":"ranqibiaoList"
                    }
                ],
                "menu":"燃气表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"水表管理",
                        "menuJump":"列表",
                        "tableName":"shuibiao"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"
                        ],
                        "menu":"水表缴费管理",
                        "menuJump":"列表",
                        "tableName":"shuibiaoList"
                    }
                ],
                "menu":"水表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"油卡管理",
                        "menuJump":"列表",
                        "tableName":"youka"
                    }
                    ,
                    {
                        "buttons":[
                            "删除"
                        ],
                        "menu":"油卡缴费管理",
                        "menuJump":"列表",
                        "tableName":"youkaList"
                    }
                ],
                "menu":"油卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"帮助中心管理",
                        "menuJump":"列表",
                        "tableName":"bangzhuzhongxin"
                    }
                ],
                "menu":"帮助中心管理"
            }
            ,{
                "child":[
                    {
                        "buttons": [
                            "新增",
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu": "客服管理",
                        "tableName": "kefuguanli"
                    }
                ],
                "menu":"客服管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"帮助中心类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBangzhuzhongxin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"油卡所属公司管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYouka"
                    }

                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"电表管理",
                        "menuJump":"列表",
                        "tableName":"dianbiao"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"电表缴费管理",
                        "menuJump":"列表",
                        "tableName":"dianbiaoList"
                    }
                ],
                "menu":"电表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"ETC管理",
                        "menuJump":"列表",
                        "tableName":"etc"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"ETC缴费管理",
                        "menuJump":"列表",
                        "tableName":"etcList"
                    }
                ],
                "menu":"ETC管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"供暖管理",
                        "menuJump":"列表",
                        "tableName":"gongnuan"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"供暖缴费管理",
                        "menuJump":"列表",
                        "tableName":"gongnuanList"
                    }
                ],
                "menu":"供暖管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"固话管理",
                        "menuJump":"列表",
                        "tableName":"guhua"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"固话缴费管理",
                        "menuJump":"列表",
                        "tableName":"guhuaList"
                    }
                ],
                "menu":"固话管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宽带管理",
                        "menuJump":"列表",
                        "tableName":"kuandai"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"宽带缴费管理",
                        "menuJump":"列表",
                        "tableName":"kuandaiList"
                    }
                ],
                "menu":"宽带管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"燃气表管理",
                        "menuJump":"列表",
                        "tableName":"ranqibiao"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"燃气表缴费管理",
                        "menuJump":"列表",
                        "tableName":"ranqibiaoList"
                    }
                ],
                "menu":"燃气表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"水表管理",
                        "menuJump":"列表",
                        "tableName":"shuibiao"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"水表缴费管理",
                        "menuJump":"列表",
                        "tableName":"shuibiaoList"
                    }
                ],
                "menu":"水表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"油卡管理",
                        "menuJump":"列表",
                        "tableName":"youka"
                    }
                    ,
                    {
                        "buttons":[
                        ],
                        "menu":"油卡缴费管理",
                        "menuJump":"列表",
                        "tableName":"youkaList"
                    }
                ],
                "menu":"油卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"帮助中心管理",
                        "menuJump":"列表",
                        "tableName":"bangzhuzhongxin"
                    }
                ],
                "menu":"帮助中心管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
